title: EFanZh’s Blog
description: ~
domain: efanzh.org
my-pages:
  - title: Demos & Tools
    url: /demos-and-tools.html
links:
  - title: GitHub
    url: https://github.com/EFanZh
defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        layout: "page"
gems:
  - jekyll-sitemap
