baseurl: efanzh.github.io
title: EFanZh’s Blog
description: ~
links:
  - title: GitHub
    url: https://github.com/EFanZh
defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        layout: "post"
  - scope:
        path: ""
        type: "pages"
    values:
        layout: "default"
  - scope:
        path: "scripts"
    values:
        layout: nil
